ROOT: 'output/snakemake'
ANNOTATIONS: 'annotations'
py_env : multibind
timing: false

HYPERPARAM:
    n_kernels: [1, 2, 3, 4, 5]
    w: 15
    n_epochs: 1000
    early_stopping: 100
    n_sample: 25000

EXPERIMENT:
  SELEX:
    count_data: True

#  PBM:
#    count_data: False

