ROOT: 'output/snakemake'
ANNOTATIONS: 'annotations'
py_env : multibind
timing: false

HYPERPARAM:
    # n_kernels: [1, 2, 3]
    n_kernels: [1]
    w: 15
    n_epochs: 12
    early_stopping: 100
    n_sample: 100 

EXPERIMENT:
  SELEX:
    count_data: True

#  PBM:
#    count_data: False

