name: scvi
channels:
    - conda-forge
    - anaconda
    - bioconda
dependencies:
    - python>=3.8.1
      #     - jupyterlab
      #     - pandas
      #     - scikit-learn
      #     - statsmodels
      #    - scipy
      #    - logomaker
      #     - pytorch
      #     - numpy
      #    - seaborn
      #    - scanpy
